### ISSUE TITLE
No weather icon, temperature shows up as -273°C, despite having entered API key and city ID

### ISSUE THREAD

**Issue by rykemasters** [sstojkovic/eleg-weather-conky#2]
As the title says, I plug in my API key and city ID in weather.sh, and the result:

![image](https://user-images.githubusercontent.com/91340297/134714365-8bb9f3b5-dcf5-4d7d-873a-c62cc4c1bbbc.png)

If I plug the api number and city ID into the URL, it returns the correct data. It might be relevant to mention that I'm using conky-manager2 (compatible with the new lua scripts) to manage my conky.

I feel like I must be forgetting something silly about configuring the file, but there's no mention of doing anything else in the readme.

**Comment by rykemasters** [comment]
False alarm: I had not installed jq as specified in the readme. Derp.

**Comment by sstojkovic** [comment]
@rykemasters 
No problem, I`m glad it worked out.
